export default {
	FETCH_PARTICIPANTS: 'FETCH_PARTICIPANTS',
	SAVE_PARTICIPANT: 'SAVE_PARTICIPANT',
	FETCH_PARTICIPANTS_FULFILLED: 'FETCH_PARTICIPANTS_FULFILLED',
	SAVE_PARTICIPANT_FULFILLED: 'SAVE_PARTICIPANT_FULFILLED',
	UPDATE_CONTACT_FULFILLED: 'UPDATE_CONTACT_FULFILLED',
	UPDATE_CONTACT_REJECTED: 'UPDATE_CONTACT_REJECTED'


}